version: "3"
services:
  mysql:
    build: ./dockerfiles/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '13306:3306'
    volumes:
      - ./dockerfiles/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
  
  nginx:
    build: ./dockerfiles/nginx/
    ports:
      - '8088:80'
