# Generated by Django 2.2.1 on 2019-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x1037a96a8>', max_length=40),
        ),
    ]
