# Generated by Django 2.2.1 on 2019-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20190511_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='cce7f1ba-47f8-4e54-92e7-0ddd9adf0ccf', max_length=40),
        ),
    ]
