# Generated by Django 2.2.1 on 2019-05-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20190511_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='b555c400-385d-4d85-a476-f289b4088e52', max_length=40),
        ),
    ]
