# Generated by Django 2.2.1 on 2019-05-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20190512_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='3b5e599f-697a-48ae-816b-cf73f29cf008', max_length=40),
        ),
    ]
