# Generated by Django 2.2.1 on 2019-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20190512_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='3754879c-31f6-49d6-8bd4-a63d7825658f', max_length=40),
        ),
    ]
