# Generated by Django 2.2.1 on 2019-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20190512_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='fbdfe3cb-7515-49f7-8e2d-7d1dec526e2b', max_length=40),
        ),
    ]
