# Generated by Django 2.2.1 on 2019-05-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20190512_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='1fed39f1-37d1-4ffd-8841-6479a8813ea7', max_length=40),
        ),
    ]
