# Generated by Django 2.2.1 on 2019-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20190513_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='6c06b210-8833-4b3b-9f96-c277283471be', max_length=40),
        ),
    ]
