# Generated by Django 2.2.1 on 2019-05-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20190513_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='a9116717-e46f-4b7f-bc5b-e090ff661e78', max_length=40),
        ),
    ]
