# Generated by Django 2.2.1 on 2019-05-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_auto_20190513_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='8d890898-3f8c-4300-ae38-925ccf28e45a', max_length=40),
        ),
    ]
