# Generated by Django 2.2.1 on 2019-05-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_auto_20190514_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='220a5620-2f50-4513-b85c-12447d1b7b0b', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
