# Generated by Django 2.2.1 on 2019-05-14 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_auto_20190514_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.TextField()),
                ('article_id', models.IntegerField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='1382f7de-d9db-4ced-9e3c-635635ced877', max_length=40),
        ),
    ]
