# Generated by Django 2.2.1 on 2019-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_auto_20190514_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecover',
            name='article_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='9a50f641-5312-49cc-89f9-d7d590be92e1', max_length=40),
        ),
    ]
