# Generated by Django 2.2.1 on 2019-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_auto_20190514_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='4b608f3a-4a5e-4a2b-836d-5a867610e8cd', max_length=40),
        ),
    ]
