# Generated by Django 2.2.1 on 2019-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_auto_20190514_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='e4c74835-f3f1-4c99-a529-bb37c9b7b085', max_length=40),
        ),
    ]
