# Generated by Django 2.2.1 on 2019-05-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_auto_20190514_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='1a147854-4a3e-4c7b-8af2-654f10ad7929', max_length=40),
        ),
    ]
