# Generated by Django 2.2.1 on 2019-05-14 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_auto_20190514_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('img_type', models.CharField(max_length=10)),
                ('article_id', models.IntegerField(default=-1)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.DeleteModel(
            name='ArticleCover',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='a0127ec3-ba25-4f85-99cb-ab8640ec6cec', max_length=40),
        ),
    ]
