# Generated by Django 2.2.1 on 2019-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_auto_20190514_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='b8554d6d-264a-4ce7-bd9b-a2e1e218a13d', max_length=40),
        ),
    ]
