# Generated by Django 2.2.1 on 2019-05-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_auto_20190514_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='prefer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='12f3858e-06af-418c-acc6-676ac901e50f', max_length=40),
        ),
        migrations.CreateModel(
            name='CollectedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Article')),
            ],
        ),
    ]
