# Generated by Django 2.2.1 on 2019-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_auto_20190515_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='8896d932-4694-49f3-92c3-cfe9f641e25b', max_length=40),
        ),
    ]
