# Generated by Django 2.2.1 on 2019-05-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_remove_user_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
