# Generated by Django 2.2.1 on 2019-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_auto_20190515_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbUpArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
